# Generated by Django 3.0.2 on 2020-01-27 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking_spot', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Entry',
            new_name='Entries',
        ),
        migrations.RenameModel(
            old_name='Stats',
            new_name='Statistics',
        ),
    ]
