# Generated by Django 3.0.1 on 2020-02-02 21:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('parking_spot', '0002_auto_20200127_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='entries',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
